Modified Cloudbuild file

diff --git a/Pipeline/cloudbuild.yaml b/Pipeline/cloudbuild.yaml
--- a/Pipeline/cloudbuild.yaml
+++ b/Pipeline/cloudbuild.yaml
@@ -83,19 +83,23 @@ steps:
 
         echo "✔ Docker container 'my-app' is running."
 
-        for i in {1..20}; do
-          HTTP_CODE=$$(curl -o /dev/null -s -w "%{http_code}" http://localhost:3000)  # Check localhost or $$CONTAINER_IP
-          if [ "$$HTTP_CODE" -eq 200 ]; then
-            echo "✔ Website is up and running!"
-            exit 0
+        echo "Checking application status..."
+        for i in {1..3}; do
+          RESPONSE=$$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
+          if [ "$$RESPONSE" -eq 200 ]; then
+            echo "✔ Application page is accessible"
+            break
           fi
-          echo "Attempt $$i: Website not ready yet. HTTP status: $$HTTP_CODE. Retrying in 10 seconds..."
-          sleep 10
+          echo "Attempt $$i: Application not accessible yet. HTTP status: $$RESPONSE. Retrying in 5 seconds..."
+          sleep 5
         done
 
-        echo "Website did not become accessible within the allocated time."
-        docker logs my-app
-        exit 1
+        # Check final response
+        if [ "$$RESPONSE" -ne 200 ]; then
+          echo "Failed to access application page. HTTP status code: $$RESPONSE"
+          docker logs test-container  # Print logs for debugging
+          exit 1
+        fi
 
   - name: "gcr.io/cloud-builders/docker"
     entrypoint: "bash"
